[package]
name = "Chat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["unstable"] }
tokio = {version = "1.38.0", features = ["sync"]}
serde = {version = "1.0.203", features = ["derive", "rc"]}
serde_json = "1.0.120"
